gluster/build-jobs

build-gluster-org/scripts/32-bit-build-smoke.sh
While this should be shared with others jobs, there is no easy way as far as I know
=> Refactor the script

build-gluster-org/jobs/planet.yml
This should fix the issue of not building PR properly
=> Use the SHA1 when building

build-gluster-org/jobs/planet.yml
(just did the same error 2 days ago...)
=> Revert, cause we need to access http.int for planet

build-gluster-org/scripts/nightly-master.dsl
Signed-off-by: Rakshitha Kamath <rkamath@redhat.com>
=> Changes to nightly-master for sending email

build-gluster-org/jobs/centos7-regression.yml, build-gluster-org/scripts/centos-regression.sh
This will allow reviewers to look at tests which needed retry,
and also the tests which are flaky.
Updates: gluster/project-infrastructure#72
Change-Id: I9d5db026bc47d612b05fc74622f1e0c000ba4f35
Signed-off-by: Amar Tumballi <amar@kadalu.io>
=> Add regression output in case of success too

requirements.txt
I think we no longer need to use a custom version
=> Revert the temporary hack

build-gluster-org/jobs/python-lint.yml
To merge if https://build.gluster.org/job/gh_python-lint/68/console is successful
=> Move the job to fedora 32

build-gluster-org/scripts/clang.sh
See gluster/project-infrastructure/issues/90
=> Add missing deps, libuuid-devel

build-gluster-org/scripts/regression-abort.sh, build-gluster-org/scripts/rpm-cleanup.sh
Related to https://github.com/gluster/project-infrastructure/issues/102
=> Cleanup the builder when the run is aborted

build-gluster-org/scripts/clang-format.py
Change-Id: I47c0f43ac686819cacbc506a4cd8df7581fcc699
Signed-off-by: Amar Tumballi <amar@kadalu.io>
=> clang-format: pick the proper set of files while checking

build-gluster-org/jobs/strfmt_errors.yml
Issue: https://github.com/gluster/project-infrastructure/issues/113
=> Add post build task to strfmt_errors job

build-gluster-org/jobs/32-bit-build-smoke.yml, build-gluster-org/jobs/centos7-regression.yml, build-gluster-org/jobs/clang-format.yml, build-gluster-org/jobs/devrpms.yml, build-gluster-org/jobs/fedora-smoke.yml, build-gluster-org/jobs/freebsd-smoke.yml, build-gluster-org/jobs/python-compliance.yml, build-gluster-org/jobs/python-lint.yml, build-gluster-org/jobs/regression-on-demand-full-run.yml, build-gluster-org/jobs/regression-on-demand-multiplex.yml, build-gluster-org/jobs/regression-test-burn-in.yml, build-gluster-org/jobs/regression-test-with-multiplex.yml, build-gluster-org/jobs/shellcheck.yml, build-gluster-org/jobs/smoke.yml, build-gluster-org/jobs/strfmt_errors.yml
Hi @deepshikhaaa / @mscherer ,
Please review this PR.
Regards,
Rakshitha Kamath
=> Updated the job description of Github jobs

build-gluster-org/jobs/glusto-tests-lint.yml
=> Revert " Remove org-list & allow-whitelist-orgs-as-admins from glusto-tests-l…"

build-gluster-org/jobs/planet.yml, build-gluster-org/scripts/planet.sh
See https://github.com/gluster/project-infrastructure/issues/118
=> Fix planet build

build-gluster-org/jobs/centos7-regression.yml
Hi @mscherer,
Please review this PR.
Thank you.
=> Disabled the job centos7-regression (resolves: issue #89)

build-gluster-org/jobs/clang-format.yml
Hi @mscherer,
Please review this PR.
Thank you.
=> Disabled the job clang-format (resolves: issue #92)

build-gluster-org/jobs/clang.yml
It still run on F32 chroot for now
=> Move the build to the F34 host

build-gluster-org/jobs/centos7-regression.yml, build-gluster-org/jobs/clang-format.yml
Hi @deepshikhaaa 
Please do review this PR.
Thank you.
=> Enabled the jobs - centos7-regression and gh_clang-format

build-gluster-org/jobs/lcov.yml
Hi @deepshikhaaa @mscherer ,
Please review this PR.
Regards,
Rakshitha Kamath
=> Fix to line-coverage job failure

build-gluster-org/scripts/32-bit-build-smoke.sh, build-gluster-org/scripts/glusterfs-devrpms.sh, build-gluster-org/scripts/strfmt_errors.sh
Issue reference: https://github.com/gluster/project-infrastructure/issues/140
=> Add options to enable tcmalloc for mock build

build-gluster-org/scripts/glusterfs-rpms.sh
Issue reference: https://github.com/gluster/project-infrastructure/issues/140
=> Add options to enable tcmalloc for mock build (job_name: rpm-el7)

build-gluster-org/scripts/clang.sh
=> added tcmalloc dependency

build-gluster-org/jobs/macros.yml, build-gluster-org/jobs/smoke-template.yml, build-gluster-org/jobs/strfmt_errors.yml, build-gluster-org/scripts/32-bit-build-smoke.sh, build-gluster-org/scripts/strfmt_errors.sh
Hi @mscherer and @deepshikhaaa,
Please do review this PR.
=> Providing fix to the issue #154

build-gluster-org/scripts/32-bit-build-smoke.sh
Should fix https://github.com/gluster/project-infrastructure/issues/159
=> Add openssl, needed since configure call the binary
